version: "3.8"

services:
  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: kids-memory-game-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: kids-memory-game
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/kids-memory-game --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: kids-memory-game-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/kids-memory-game
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    command: npm run start:dev

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
